SASRU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = staticfiles_urlpatterns()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('banco/', include ('apps.banco.urls', namespace="banco")),
    path('Rfid/', include ('apps.Rfid.urls', namespace="rfid")),
    path('usuarios/', include ('apps.usuarios.urls', namespace="usuarios")),
    path('', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/reset/password_reset', auth_views.PasswordResetView.as_view(), name= 'password_reset'),
    #auth_views.PasswordResetForm.as_view(),
    path('accounts/reset/password_reset_confirm', auth_views.PasswordChangeDoneView.as_view(), name= 'password_reset_done'),
     path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name= 'password_reset_confirm'),
    path('accounts/reset/done', auth_views. PasswordResetCompleteView.as_view(), name= 'password_reset_complete'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Rfid/urls.py
from django.urls import path, include
from django.contrib import admin
from apps.Rfid.views import LecturaUid, inicioRfid, Actualizar_Saldo, autorizar, inicioAutorizar, descuento_autorizacion, prueba, vistacupos
from django.contrib.auth.decorators import login_required


app_name = 'variable123'



urlpatterns = [
path('inicio/lectura/', login_required (LecturaUid),name='index3'),
path('inicio/',login_required ( inicioRfid),name='inicio'),
path('editar/<int:pk>/',login_required(Actualizar_Saldo.as_view()),name='saldo_editar'),
path('inicio/',login_required (inicioRfid),name='inicio'),
path('inicio/autorizar',login_required ( inicioAutorizar),name='inicio_autorizar'),
path('Autorizar/', login_required (autorizar),name='autorizacion'),
path('Autorizar/descuento/<int:id_usuario>/',login_required (descuento_autorizacion),name='descuento_autorizacion'),
path('prueba/', login_required (vistacupos),name='vista_cupos'),
path('redimir/',login_required (prueba) ,name='redimir'),







]

apps/banco/urls.py
from django.urls import path, include
from django.contrib import admin
from apps.Rfid.views import CuposCreate, mostrar , vistacupos
from apps.banco.views import index, banco_view,Bancolist, BuscarView, index_1, search, lista_transacciones, BuscarRecarga
from django.contrib.auth.decorators import login_required


app_name = 'variable12'
urlpatterns = [
    path('', index,name='index'),
    path('nuevo/',login_required (banco_view), name='banco_crear'),
    path('nuevo/lista', login_required (Bancolist.as_view()), name='banco_lista'),
    path('nuevo/busquedas/', login_required ( BuscarView.as_view()),name='buscarlo'),
    path('n', index_1,name='index_usuarios'),
    path('busqueda', search,name='search'),
    path('listasapi',  lista_transacciones,name='api'),
    #path('inicio',  login_required(CuposCreate.as_view()),name='setpoint'),
    path('inicio2',  login_required(mostrar),name='setpoint1'),
    path('inicio3',  login_required(vistacupos),name='setpointview'),
    path('nuevo/busquedas1/', login_required ( BuscarRecarga.as_view()),name='buscar_recarga'),




]

apps/usuarios/urls.py
from django.urls import path, include
from django.contrib import admin
from apps.usuarios.views import index_usuarios, Usuarioslist, Usuarios_Crear, Usuarios_Actualizar, Usuarios_Eliminar, RegistroUsuario, usuarios_list, listadousuarios,BuscarView, \
crear_trans, usuario_crear, Ilogin, ProfileUpdate
from django.contrib.auth.decorators import login_required


app_name = 'variable3'
urlpatterns = [


    #path('', index_usuarios,name='index_usuarios'),
    path('nuevo/lista', login_required( usuarios_list),name='usuario_listas'),
    #path('nuevo', login_required(Usuarios_Crear.as_view()),name='usuario_crear'),
    path('nuevo', login_required(usuario_crear),name='usuario_crear'),
    path('editar/<int:pk>/',login_required(Usuarios_Actualizar.as_view()),name='usuario_editar'),
    path('eliminar/<int:pk>/',login_required( Usuarios_Eliminar.as_view()),name='usuario_eliminar'),
    path('registro/nuevo', RegistroUsuario.as_view(),name='usuario_registro'),
    path('listao', listadousuarios,name='index_list'),
    #path('Api', UserApi.as_view(),name='api'),
    path('nuevo/busquedas/',  BuscarView.as_view(),name='buscarlo'),
    path('transaccion/<int:id_usuario>/', crear_trans,name='crear_trans'),


    path('profile/', ProfileUpdate.as_view(), name="profile" ),




]

proyecto_ejemplo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', admin.site.urls),
]

templates/base/base1.html
{%load staticfiles %}
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <title> {% block title %}  {% endblock %} | SASRU</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'Usco_logo.png' %}"/>


    <meta charset="utf-8">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>
    <script>
      $(document).ready( function () {
      $('#mytable').DataTable( {
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
        }
          } );
      } );

    </script>




  </head>
  <body >




      {% block navbar %}

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'banco:setpoint1' %}">
          <img src="{% static 'imagenes/Usco_logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          SASRU
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'banco:setpoint1' %}">Inicio <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">

              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Recarga
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"   href="{% url 'banco:banco_crear' %}"> Manual </a>
                <a class="dropdown-item"  href="{% url 'rfid:inicio' %}"> RFID</a>
              </div>
            </li>




            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              RFID
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item"  href="{% url 'rfid:inicio_autorizar' %}">Validación</a>
            </div>
          </li>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Estadisticas
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'banco:banco_lista' %}">Lista de Transacciones</a>
                <a class="dropdown-item" href="{% url 'usuarios:usuario_listas' %}">Lista de Usuarios</a>
                <a class="dropdown-item" href="{% url 'rfid:vista_cupos' %}">Cupos disponibles del dia </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'usuarios:usuario_registro' %}">Registro de Usuario Admin</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'usuarios:usuario_crear' %}">Nuevo Usuario </a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0 "  method="POST"  action="busquedas/">
            <input class="form-control mr-sm-2 " name="buscalo" type="search" placeholder="Busca por codigo o c.c" aria-label="Busqueda ">{% csrf_token %}
            <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">Busqueda</button>
          </form>
        </div>



          <form class="form-inline">

          <a href="{% url 'logout' %}" class="btn btn-primary btn-sm " role="button" > Cerrar sesion</a>


          </form>


      </nav>
      {% endblock %}


<div class="container">
   {% block content %}

   <h5> Este es el contenido del archivo base </h5>

   {% endblock %}

   {% block footer %}
   {% endblock  %}


  </div>




  </body>
</html>

templates/base/base_recarga.html
{%load staticfiles %}
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <link rel="shortcut icon" type="image/png" href="{% static 'Usco_logo.png' %}"/>
    <title>{% block title %}  {% endblock %} | SASRU</title>

    <meta charset="utf-8">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">

    </script>

    <script type="text/javascript" src="{% static 'js/ajax.js' %}">

    </script>



  </head>
  <body >




      {% block navbar %}

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'banco:setpoint1' %}">
          <img src="{% static 'imagenes/Usco_logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          SASRU
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">





            <li class="nav-item dropdown">

              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Recarga
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"   href="{% url 'banco:banco_crear' %}"> Manual </a>
                <a class="dropdown-item"  href="{% url 'rfid:inicio' %}"> RFID</a>
              </div>
            </li>

















            <li class="nav-item dropdown">

              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                RFID
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"  href="{% url 'rfid:inicio_autorizar' %}">Validación</a>
              </div>
            </li>





                <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Estadisticas
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'banco:banco_lista' %}">Lista de Transacciones</a>
                <a class="dropdown-item" href="{% url 'usuarios:usuario_listas' %}">Lista de Usuarios</a>
                <a class="dropdown-item" href="{% url 'rfid:vista_cupos' %}">Cupos disponibles del dia </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'usuarios:usuario_registro' %}">Registro de Usuario</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'usuarios:usuario_crear' %}">Nuevo Usuario </a>
            </li>

          </ul>
          <form class="form-inline my-2 my-lg-0 "  method="POST"  action="busquedas1/">
            <input class="form-control mr-sm-2 " name="buscalo" type="search" placeholder="Busqueda por codigo" aria-label="Busqueda ">{% csrf_token %}
            <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">Busqueda</button>
          </form>
        </div>



          <form class="form-inline">

          <a href="{% url 'logout' %}" class="btn btn-primary btn-sm " role="button" > Cerrar sesion</a>


          </form>


      </nav>
      {% endblock %}


<div class="container">
   {% block content %}

   <h5> Este es el contenido del archivo base </h5>

   {% endblock %}

   {% block footer %}
   {% endblock  %}


  </div>




  </body>
</html>