SASRU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = staticfiles_urlpatterns()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('banco/', include ('apps.banco.urls', namespace="banco")),
    path('Rfid/', include ('apps.Rfid.urls', namespace="rfid")),
    path('usuarios/', include ('apps.usuarios.urls', namespace="usuarios")),
    path('', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/reset/password_reset', auth_views.PasswordResetView.as_view(), name= 'password_reset'),
    #auth_views.PasswordResetForm.as_view(),
    path('accounts/reset/password_reset_confirm', auth_views.PasswordChangeDoneView.as_view(), name= 'password_reset_done'),
     path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name= 'password_reset_confirm'),
    path('accounts/reset/done', auth_views. PasswordResetCompleteView.as_view(), name= 'password_reset_complete'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/urls.py
from django.urls import path, include
from django.contrib import admin
from apps.usuarios.views import index_usuarios, Usuarioslist, Usuarios_Crear, Usuarios_Actualizar, Usuarios_Eliminar, RegistroUsuario, usuarios_list, listadousuarios,BuscarView, \
crear_trans, usuario_crear, Ilogin, ProfileUpdate
from django.contrib.auth.decorators import login_required


app_name = 'variable3'
urlpatterns = [


    #path('', index_usuarios,name='index_usuarios'),
    path('nuevo/lista', login_required( usuarios_list),name='usuario_listas'),
    #path('nuevo', login_required(Usuarios_Crear.as_view()),name='usuario_crear'),
    path('nuevo', login_required(usuario_crear),name='usuario_crear'),
    path('editar/<int:pk>/',login_required(Usuarios_Actualizar.as_view()),name='usuario_editar'),
    path('eliminar/<int:pk>/',login_required( Usuarios_Eliminar.as_view()),name='usuario_eliminar'),
    path('registro/nuevo', RegistroUsuario.as_view(),name='usuario_registro'),
    path('listao', listadousuarios,name='index_list'),
    #path('Api', UserApi.as_view(),name='api'),
    path('nuevo/busquedas/',  BuscarView.as_view(),name='buscarlo'),
    path('transaccion/<int:id_usuario>/', crear_trans,name='crear_trans'),


    path('profile/', ProfileUpdate.as_view(), name="profile" ),




]

proyecto_ejemplo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', admin.site.urls),
]

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Usuario(models.Model):


    nombre = models.CharField(max_length=15 )
    apellidos = models.CharField(max_length=20)
    foto = models.ImageField(upload_to='photos', null= True, blank = True)
    cedula = models.CharField(max_length=12)
    codigo = models.CharField(max_length=11)
    programa = models.CharField(max_length=25)
    uid = models.CharField(max_length=20)
    email = models.EmailField()
    saldo = models.PositiveIntegerField(null=False, blank=True,default=0)
    reserva_desayuno= models.BooleanField(default=False)
    reserva_almuerzo= models.BooleanField(default=False)
    reserva_cena= models.BooleanField(default=False)
    sancion= models.BooleanField(default=False)
    comida_consumida=models.BooleanField(default=False)



    def __str__(self):
        return '{} {} {}'.format(self.apellidos, self.nombre, self.uid)


#class Tipo_de_transaccion(models.Model):

        #tipo = models.CharField(max_length=50)


        #def __str__(self):
                #return '{} '.format(self.tipo)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='profiles', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    link = models.URLField(max_length=200, null=True, blank=True)

    class Meta:
        ordering = ['user__username']

apps/usuarios/views.py
from django.shortcuts import render, redirect
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from apps.usuarios.models import Usuario
from apps.banco.models import Transaccion
from django import forms
from django.urls import reverse_lazy
from apps.usuarios.form import usuarios_form, ProfileForm
#from rest_framework.views import APIView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from apps.usuarios.forms_user import RegistroForm
from apps.banco.form import TransaccionForm
from .models import Profile
from django.core import serializers
import json
#from rest_framework.views import APIView
#from apps.usuarios.serializer import UserSerializer





# Create your views here.

def listadousuarios(request):
    lista=serializers.serialize('json', Usuario.objects.all(), fields= ['username','first_name'])
    return HttpResponse(lista, content_type='application/json')




def index_usuarios(request):
    return HttpResponse("SOY LA PAGINA PRINCIPAL DE LA APLICACION")


def index_1(request):
    return   render(request,'pruebas/prueba.html' )



class Usuarioslist(ListView):
    usuario = Usuario.objects.all().order_by('id')

    model= Usuario
    template_name= 'usuarios/usuarios_list.html'

def usuarios_list(request):
    usuario = Usuario.objects.all().order_by('id')
    contexto = {'usuarios': usuario}
    return render(request, 'usuarios/usuarios_list0.html', contexto)


class Usuarios_Crear(CreateView):

    model= Usuario
    form_class= usuarios_form
    template_name='usuarios/usuarios_form.html'
    success_url= reverse_lazy('usuarios:usuario_listas')

def usuario_crear(request):
    #obtener= Usuario()
    if request.method == 'POST' :
        form= usuarios_form(request.POST, request.FILES)
        #obtener.foto = request.FILES.get('txtImagen')
        if form.is_valid():
            form.save()
            #obtener.save()
        return redirect('usuarios:usuario_listas')
    else:
        form= usuarios_form()
    return render(request,'usuarios/usuarios_form.html', {'form':form }      )







class Usuarios_Actualizar(UpdateView):
    model= Usuario
    form_class= usuarios_form
    template_name='usuarios/usuarios_form.html'
    success_url= reverse_lazy('usuarios:usuario_listas')

class Usuarios_Eliminar(DeleteView):
    model= Usuario
    form_class= usuarios_form
    template_name='usuarios/usuarios_delete.html'
    success_url= reverse_lazy('usuarios:usuario_listas')

class RegistroUsuario(CreateView):
	model = User
	template_name = "usuarios/registrar.html"
	form_class = RegistroForm
	success_url = reverse_lazy('usuarios:usuario_listas')



"""
class UserApi(APIView):
	serializer= UserSerializer
	def get (self, request, format=None ):

		lista = User.objects.all()

		response = self.serializer(lista, many=True)

		return HttpResponse(json.dumps(response.data), content_type='application/json')
"""

class BuscarView(TemplateView):
    def post(self, request, *args, **kwargs):
        buscar= request.POST['buscalo']
        usuario2= Usuario.objects.filter(codigo__contains=buscar)
        usuario3= Usuario.objects.filter(cedula__contains=buscar)
        if usuario2:
            print ("ha buscado por su apellido")
            print(usuario2)
            return   render(request,'busquedas/buscar.html', {'usuario2':usuario2, 'usuari':True   } )


        elif usuario3:
            print ("ha buscado por su cedula")
            print(usuario3)
            return   render(request,'busquedas/buscar.html', {'usuario2':usuario3, 'usuari':True   } )




        else:

            return   render(request,'busquedas/buscar.html' )

def crear_trans(request,id_usuario):

    user = Transaccion.objects.filter(persona_id_id=id_usuario).exists()
    print(user)
#____





#____________________
    if user == False:
        rank=Usuario.objects.get(id=id_usuario)




        transaccion=Transaccion.objects.create(persona_id_id=id_usuario, Valor_de_transaccion=0)
        transaccion.codigo=rank.codigo
        transaccion.save()
    else:
        print(user)
        print(user)

    mascota = Transaccion.objects.filter(persona_id_id=id_usuario).first()


    if request.method == 'POST':
        form = TransaccionForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('banco:banco_lista')
    else :
        form = TransaccionForm(instance=mascota)
    return render(request, 'usuarios/usuarios_form.html', {'form': form })


class Ilogin(TemplateView):
    template_name='login/login.html'
    success_url= reverse_lazy('usuarios:usuario_listas')



@method_decorator(login_required, name='dispatch')
class ProfileUpdate(LoginRequiredMixin,UpdateView):
    model= Profile
    form_class= ProfileForm
    #fields=['avatar', 'bio', 'link']
    success_url= reverse_lazy('usuarios:profile')
    template_name= 'registration/profile_form.html'

    def get_object(self):
        #recuperar el objeto a editar
        profile, created= Profile.objects.get_or_create(user=self.request.user)
        return profile

templates/usuarios/registrar.html
{% extends 'base/base.html' %}

{% block title %} Nuevo admin  {% endblock %}


{% block content %}
<div class="container">

<h4> COMPLETE LA INFORMACION  </h4>

<form method="post">
	{% csrf_token %}
<head>
  <style type="text/css">
  body{
  }

  </style>
</head>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label>Nombre</label>
				<input class="form-control" type="text" name="first_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Apellidos</label>
				<input class="form-control" type="text" name="last_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Nombre de usuario</label>
				<input class="form-control" type="text" name="username">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Correo</label>
				<input class="form-control" type="text" name="email">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Contraseña</label>
				<input class="form-control" type="password" name="password1">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Confirmar contraseña</label>
				<input class="form-control" type="password" name="password2">
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>

</form>
{% endblock %}

templates/usuarios/usuarios_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
  <h3>¿Desea eliminar el registro de {{object.nombre}}</h3>

	<button class="btn btn-danger " type="submit">Si, eliminar</button>
  <a class="btn btn-default" href="{% url 'usuarios:usuario_listas' %}">Cancelar</a>


</form>
{% endblock %}

templates/usuarios/usuarios_form.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container">


	<h4> COMPLETE LA INFORMACION  </h4>



	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}



		<button class="btn btn-primary "type="submit">Guardar</button>
	</form>


	{% endblock %}

templates/usuarios/usuarios_list.html
{% extends 'base/base1.html' %}

{% block content %}
<div class="container">

  <script>
    $(document).ready( function () {
    $('#mytable').DataTable();
      } );

  </script>


<table class="table table-bordered table-condensed " id="mytable">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">apellidos</th>
      <th scope="col">cedula</th>
      <th scope="col">programa </th>
      <th scope="col">codigo </th>
      <th scope="col">Uid</th>
      <th scope="col">saldo</th>
      <th scope="col">Imagen</th>

      <th scope="col">Acciones</th>

    </tr>
  </thead>


	<tbody>
		{% if object_list %}
		{% for usuario in object_list %}
		<tr>
			<td>{{ usuario.id }}</td>
			<td>{{ usuario.nombre }}</td>
			<td>{{ usuario.apellidos }}</td>
			<td>{{ usuario.cedula }}</td>
			<td>{{ usuario.programa}}</td>
      <td>{{ usuario.codigo}}</td>
      <td>{{ usuario.uid}}</td>
      <td>{{ usuario.saldo}}</td>
      <td>
        {% if usuario.foto %}
        <img src="{{ usuario.foto.url}}" width="100" height="100">
        {% endif %}
      </td>






			<td>
				<a class="btn btn-primary" href="{% url 'usuarios:usuario_editar' usuario.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'usuarios:usuario_eliminar' usuario.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de transacciones</h1>
		{% endif %}
	</tbody>
</table>
{% endblock%}

templates/usuarios/usuarios_list0.html
{% extends 'base/base.html' %}

{% block title %} Lista de usuarios  {% endblock %}

{% block content %}

<br>
<br>

<div class="panel-body">



<table  width="100%" class="table table-striped table-bordered table-hover" id="mytable">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">apellidos</th>
      <th scope="col">cedula</th>
      <th scope="col">programa </th>
      <th scope="col">codigo </th>
      <th scope="col">Uid</th>
      <th scope="col">saldo</th>
      <th scope="col">Imagen</th>
      <th scope="col">Acciones</th>


    </tr>
  </thead>



	<tbody>
		{% if usuarios %}
		{% for usuario  in usuarios %}
		<tr>
      <td>{{ usuario.id }}</td>
			<td>{{ usuario.nombre }}</td>
			<td>{{ usuario.apellidos }}</td>
			<td>{{ usuario.cedula }}</td>
			<td>{{ usuario.programa}}</td>
      <td>{{ usuario.codigo}}</td>
      <td>{{ usuario.uid}}</td>
      <td>{{ usuario.saldo}}</td>
      <td>
        {% if usuario.foto %}
        <img src="{{ usuario.foto.url}}" width="100" height="100">
        {% endif %}
      </td>


			<td>
				<a class="btn btn-primary" href="{% url 'usuarios:usuario_editar' usuario.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'usuarios:usuario_eliminar' usuario.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de transacciones</h1>
		{% endif %}
	</tbody>
</table>
{% endblock%}