SASRU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = staticfiles_urlpatterns()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('banco/', include ('apps.banco.urls', namespace="banco")),
    path('Rfid/', include ('apps.Rfid.urls', namespace="rfid")),
    path('usuarios/', include ('apps.usuarios.urls', namespace="usuarios")),
    path('', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/reset/password_reset', auth_views.PasswordResetView.as_view(), name= 'password_reset'),
    #auth_views.PasswordResetForm.as_view(),
    path('accounts/reset/password_reset_confirm', auth_views.PasswordChangeDoneView.as_view(), name= 'password_reset_done'),
     path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name= 'password_reset_confirm'),
    path('accounts/reset/done', auth_views. PasswordResetCompleteView.as_view(), name= 'password_reset_complete'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Rfid/urls.py
from django.urls import path, include
from django.contrib import admin
from apps.Rfid.views import LecturaUid, inicioRfid, Actualizar_Saldo, autorizar, inicioAutorizar, descuento_autorizacion, prueba, vistacupos
from django.contrib.auth.decorators import login_required


app_name = 'variable123'



urlpatterns = [
path('inicio/lectura/', login_required (LecturaUid),name='index3'),
path('inicio/',login_required ( inicioRfid),name='inicio'),
path('editar/<int:pk>/',login_required(Actualizar_Saldo.as_view()),name='saldo_editar'),
path('inicio/',login_required (inicioRfid),name='inicio'),
path('inicio/autorizar',login_required ( inicioAutorizar),name='inicio_autorizar'),
path('Autorizar/', login_required (autorizar),name='autorizacion'),
path('Autorizar/descuento/<int:id_usuario>/',login_required (descuento_autorizacion),name='descuento_autorizacion'),
path('prueba/', login_required (vistacupos),name='vista_cupos'),
path('redimir/',login_required (prueba) ,name='redimir'),







]

apps/usuarios/urls.py
from django.urls import path, include
from django.contrib import admin
from apps.usuarios.views import index_usuarios, Usuarioslist, Usuarios_Crear, Usuarios_Actualizar, Usuarios_Eliminar, RegistroUsuario, usuarios_list, listadousuarios,BuscarView, \
crear_trans, usuario_crear, Ilogin, ProfileUpdate
from django.contrib.auth.decorators import login_required


app_name = 'variable3'
urlpatterns = [


    #path('', index_usuarios,name='index_usuarios'),
    path('nuevo/lista', login_required( usuarios_list),name='usuario_listas'),
    #path('nuevo', login_required(Usuarios_Crear.as_view()),name='usuario_crear'),
    path('nuevo', login_required(usuario_crear),name='usuario_crear'),
    path('editar/<int:pk>/',login_required(Usuarios_Actualizar.as_view()),name='usuario_editar'),
    path('eliminar/<int:pk>/',login_required( Usuarios_Eliminar.as_view()),name='usuario_eliminar'),
    path('registro/nuevo', RegistroUsuario.as_view(),name='usuario_registro'),
    path('listao', listadousuarios,name='index_list'),
    #path('Api', UserApi.as_view(),name='api'),
    path('nuevo/busquedas/',  BuscarView.as_view(),name='buscarlo'),
    path('transaccion/<int:id_usuario>/', crear_trans,name='crear_trans'),


    path('profile/', ProfileUpdate.as_view(), name="profile" ),




]

proyecto_ejemplo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', admin.site.urls),
]

apps/Rfid/models.py
from django.db import models

# Create your models here.

class Global(models.Model):
    cupos_totales= models.IntegerField(default=0)
    cupos_desayuno = models.IntegerField(default=0)
    cupos_almuerzo = models.IntegerField(default=0)
    cupos_cena = models.IntegerField(default=0)
    cupos_disponibles =  models.IntegerField(default=0)
    cupos_vendidos = models.IntegerField(default=0, editable = False)
    fecha_de_transaccion= models.DateField ( auto_now = False , auto_now_add = True )
    reservas_no_redimidas= models.IntegerField(default=0)


    def save(self,*args, **kwargs):

        if self.cupos_totales<=self.cupos_desayuno+self.cupos_almuerzo+self.cupos_cena:
            self.cupos_disponibles=self.cupos_totales

        return super(Global, self).save( *args, **kwargs)


    def __str__(self):
        return '{} '.format( self.fecha_de_transaccion)

apps/Rfid/views.py
from django.shortcuts import render
import serial
import psycopg2
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.Rfid.form import actualizar_saldo
from django.views.generic import ListView, TemplateView, UpdateView, CreateView
from apps.banco.models import Transaccion
from apps.usuarios.models import Usuario
from django.utils import timezone
import time
from apps.Rfid.models import Global
from apps.Rfid.form1 import SetForm
#from django_cron import CronJobBase, Schedule
import datetime
import logging
from django.db.models import Q
#DEFAULT_LOCK_BACKEND = 'django_cron.backends.lock.cache.CacheLock'
#logger = logging.getLogger('django_cron')


# Create your views here.

#def my_scheduled_job():
    #usuarios= Usuario.objects.filter(sancion=True).update(sancion=False)

"""
#class MyCronJob(CronJobBase):
    RUN_EVERY_MINS = 2
    MIN_NUM_FAILURES = 3

    schedule = Schedule(run_every_mins=RUN_EVERY_MINS)

    #RUN_AT_TIMES = ['00:50', '18:50', '00:25']
    #schedule = Schedule(run_at_times=RUN_AT_TIMES)
    code = 'apps.my_cron_job'

    def do(self):
        usuarios= Usuario.objects.filter(sancion=True).update(sancion=False)"""



def inicioRfid(request):
    return render(request, 'rfid/identificador_rfid.html')

def inicioAutorizar(request):

    return render(request, 'rfid/identificador_autorizacion.html')


def retornar(request):
    """
    global usuario2
    global request
    ss = True
    if ss ==  True:
        """
    return   render(request,'rfid/busqueda_rfid.html', {'usuario2':usuario2, 'usuari':True   } )


def LecturaUid(request):










    # conexion a la base de datos-----------

    try:
      #conn_string="dbname='SASRU' user='postgres' host='localhost' password='ingenieria@'
      #arduino = serial.Serial('COM8',9600, timeout=.1)


      #conn = psycopg2.connect(conn_string)
      print ("connection succeeded")
    except:

        serial.Serial('COM8',9600, timeout=.1).close()
        #print ("no connection to db")

    #cur = conn.cursor()




    #---------------------------------------------------------





    bandera=1
    arduino = serial.Serial('COM8',9600, timeout=.1)





    while 1 :

            #ELIMNAR CARACTERES DE NUEVA LINEA DE Serial.println de Arduino

            data = arduino.readline()[:-2]
            data = data.decode("utf-8")

    ##        print(data)

            if data:
                """
                print (data)
                print (type(data))
                print (len(data))
                """
                if 'UID' in data:
                        UID = data[4:]
                        print ("llego el identificador", UID)

                if 'Name' in data:
                        Nombre = data[5:]
                        print ("llego el Nombre", Nombre)
                if 'Saldo' in data:
                        Saldo = data[7:]
                        print ("llego el SALDO", Saldo )
                        print (type(Saldo))


                        Saldo_str = str(Saldo)

                        print(UID)
                        print (type(UID))
                        usuario2= Usuario.objects.filter(uid=UID)


                        bandera= 0


                        print(usuario2)
                        return   render(request,'rfid/busqueda_rfid.html', {'usuario2':usuario2, 'usuari':True   } )



            else:
                print ("no hay datos")





    #conn.close()

    #return redirect('rfid:index3')


class Actualizar_Saldo(UpdateView):


    model= Usuario
    form_class= actualizar_saldo
    template_name='rfid/Saldo_form.html'
    success_url= reverse_lazy('rfid:inicio')




def autorizar(request):







    now= datetime.datetime.now()
    hora_act=now.time()

    H1_des = datetime.time(7, 0, 0, 0)
    H2_des = datetime.time(11, 40, 0, 0)
    H1_alm = datetime.time(11, 30, 0, 0)
    H2_alm = datetime.time(13, 55, 0, 0)
    H1_cen = datetime.time(16, 00, 0, 0)
    H2_cen = datetime.time(23, 50, 0, 0)


    def Act_servicio(servicio_actual,id_usuario):
        # modificar la casilla de reseva en la base de datos
        if servicio_actual == "D":

            rank=Usuario.objects.get(id=id_usuario)
            rank.reserva_desayuno= False
            rank.save()

            #transaccion=Transaccion.objects.update(persona_id_id=id_usuario, Valor_de_transaccion=1, tipo_de_transaccion=2,codigo=rank.codigo)



        elif servicio_actual == "A" :
            rank=Usuario.objects.get(id=id_usuario)
            rank.reserva_desayuno= False
            rank.save()





    def servicio(hora_act,D,A,C):
        servicio  = False
        Act_servicio= False
        comida = ""
        print(hora_act)

        print("hola")
        # aca se verificara si el servicio esta habilitado
        if hora_act > H1_des and hora_act < H2_des:
            print("desayuno")

            comida = "Desayuno"
            if D == True:
                servicio = True
                servicio_actual= "D"
                #Act_servicio(servicio_actual)

            else:
                servicio = False

        elif hora_act > H1_alm and hora_act < H2_alm:
            print("almuerzo")
            comida = "Almuerzo"
            if A == True:
                servicio = True
                servicio_actual = 1
                #Act_servicio(servicio_actual)

            else:
                servicio = False



        elif hora_act > H1_cen and hora_act < H2_cen:
            comida = "Cena"
            print("chao")
            if C == True:

                servicio = True
                servicio_actual= "C"



            else:
                servicio = False





        return servicio, comida











    #---------------------------------------------------------

    # Realizar query a database / UID

    try:
      conn_string="dbname='SASRU' user='postgres' host='localhost' password='ingenieria@'"
      print ("Connecting to database\n->%s" % (conn_string))

      conn = psycopg2.connect(conn_string)
      print ("connection succeeded")
    except:
      print ("no connection to db")

    cur = conn.cursor()




    #---------------------------------------------------------




    arduino = serial.Serial('COM8',9600, timeout=.1)


    while True:
            #ELIMNAR CARACTERES DE NUEVA LINEA DE Serial.println de Arduino

            data = arduino.readline()[:-2]
            data = data.decode("utf-8")
    ##        print(data)

            if data:
                """
                print (data)
                print (type(data))
                print (len(data))
                """
                if 'UID' in data:
                        UID = data[4:]
                        print ("llego el identificador", UID)



                if 'Name' in data:
                        Nombre = data[5:]
                        print ("llego el Nombre", Nombre)
                if 'Saldo' in data:
                        Saldo = data[7:]
                        print ("llego el SALDO", Saldo )
                        print (type(Saldo))


                        Saldo_str = str(Saldo)

                        print(UID)

                        validacion1 = Usuario.objects.filter(uid=UID).exists()

                        if validacion1 is False:
                            print("No es valida la tarjeta")
                            nombre_servicio="por ahora"


                            return   render(request,'rfid/autorizacion.html',  {'nombre_servicio':nombre_servicio, 'resulta':True    })

                        else:

                            user=Usuario.objects.get(uid=UID)
                            user1=Usuario.objects.filter(uid=UID)

                            D = user.reserva_desayuno
                            A = user.reserva_almuerzo
                            C = user.reserva_cena

                            print("Reserva Desayuno: ", D)
                            print("Reserva Almuerzo: ", A)
                            print("Reserva Comida: ", C)




                            result, nombre_servicio = servicio(hora_act,D,A,C)

                            print(result)
                            print(result)
                            print(nombre_servicio)
                            print(user1)



                            if(result == True):
                                print("Tiene servicio", nombre_servicio)
                            else:
                                print("NO tiene servicio",nombre_servicio)







                        return   render(request,'rfid/autorizacion.html',  {'nombre_servicio':nombre_servicio, 'user1':user1, 'result':result   })



            else:
                print ("no hay datos")






    conn.close()






def descuento_autorizacion(request,id_usuario):


    now= datetime.datetime.now()
    hora_act=now.time()
    fecha_act= now.date()

    H1_des = datetime.time(7, 0, 0, 0)
    H2_des = datetime.time(11, 40, 0, 0)
    H1_alm = datetime.time(11, 30, 0, 0)
    H2_alm = datetime.time(13, 55, 0, 0)
    H1_cen = datetime.time(16, 00, 0, 0)
    H2_cen = datetime.time(23, 50, 0, 0)

    rank=Usuario.objects.get(id=id_usuario)
    rank.comida_consumida= True
    rank.sancion= True


    rank.save()

    transaccion=Transaccion.objects.create(persona_id_id=id_usuario, Valor_de_transaccion=1100, tipo_de_transaccion=2,codigo=rank.codigo)
    cuposedit=Global.objects.get(fecha_de_transaccion=fecha_act)





    if  hora_act > H1_des and hora_act < H2_des:

        cuposedit.cupos_disponibles-=1
        #cuposedit.cupos_desayuno-=1
        cuposedit.save()

        rank=Usuario.objects.get(id=id_usuario)
        rank.reserva_desayuno= False

        rank.save()


        #transaccion=Transaccion.objects.update(persona_id_id=id_usuario, Valor_de_transaccion=1, tipo_de_transaccion=2,codigo=rank.codigo)



    elif  hora_act > H1_alm and hora_act < H2_alm:

templates/rfid/Saldo_form.html
{% extends 'rfid/busqueda_rfid.html' %}

{% block content %}

<div class="container">


<h4> COMPLETE LA INFORMACION  </h4>



<form method="post">
	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit">Registrar</button>


</form>

<h4></h4>
<h4></h4>
{% endblock %}

templates/rfid/autorizacion.html
{% extends 'rfid/identificador_rfid.html' %}
{% block title %} Autorizacion  {% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
  <div class="jumbotron">
    <h3 class="text-center">IDENTIFICADOR RFID  <div class="col-12"</h3>

      <form class="form-center"    action="/Rfid/Autorizar" >
        <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">ACTIVAR</button>
      </form>

  </div>
    </div>
      </div>



{% endblock%}


{% block footer %}
<div class="container">




   {% if result == True  %}



      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">apellidos</th>
            <th scope="col">codigo</th>
            <th scope="col">programa </th>
            <th scope="col">Uid</th>
            <th scope="col">Saldo</th>
            <th scope="col">Estado</th>

            <th scope="col">Acciones</th>




           </tr>

         </thead>
         <tbody>

   {% for usuario in user1 %}
      <tr>

                     <td>{{ usuario.id }}</td>
                     <td>{{ usuario.nombre }}</td>
                     <td>{{ usuario.apellidos }}</td>
                     <td>{{ usuario.codigo }}</td>
                     <td>{{ usuario.programa}}</td>
                     <td>{{ usuario.uid}}</td>
                     <td>{{ usuario.saldo}}</td>
                     <td> Tiene servicio de {{  nombre_servicio }}</td>



                           <td>
                             <a class="btn btn-primary" href="{% url  'rfid:descuento_autorizacion' usuario.id %}">Validar</a>
                            <!-- <a class="btn btn-primary" href="{% url 'rfid:saldo_editar' usuario.id %}">Editar</a>   --->
                           </td>
                         </tr>





                            <div class="row justify-content-center">

                             {% if usuario.foto %}
                             <img class="center" src="{{ usuario.foto.url}}" width="190" height="190" display="block">

                             {% endif %}








   {% endfor %}
 <tr>
<br>
    {% elif resulta == True %}

    <h1>No es valida la tarjeta </h1>


    {% elif result == False %}


    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nombre</th>
          <th scope="col">apellidos</th>
          <th scope="col">codigo</th>
          <th scope="col">programa </th>
          <th scope="col">Uid</th>
          <th scope="col">Saldo</th>
          <th scope="col">Estado</th>






         </tr>

       </thead>
       <tbody>

 {% for usuario in user1 %}
    <tr>

                   <td>{{ usuario.id }}</td>
                   <td>{{ usuario.nombre }}</td>
                   <td>{{ usuario.apellidos }}</td>
                   <td>{{ usuario.codigo }}</td>
                   <td>{{ usuario.programa}}</td>
                   <td>{{ usuario.uid}}</td>
                   <td>{{ usuario.saldo}}</td>
                   <td> No tiene servicio  {{  nombre_servicio }}</td>









                          <div class="row justify-content-center">

                           {% if usuario.foto %}
                           <img class="center" src="{{ usuario.foto.url}}" width="190" height="190" display="block">

                           {% endif %}








 {% endfor %}
<tr>
<br>





 {% endif %}


</tbody>
</table>
{% endblock%}

templates/rfid/busqueda_rfid.html
{% extends 'rfid/identificador_rfid.html' %}


{% block title %}Identificador Rfid  {% endblock %}

{% block footer %}
<div class="container">




   {% if usuario2  %}


      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">apellidos</th>
            <th scope="col">cedula</th>
            <th scope="col">programa </th>
            <th scope="col">Uid</th>
            <th scope="col">Saldo</th>
            <th scope="col">Acciones</th>




        		</tr>

        	</thead>
        	<tbody>

   {% for usuario in usuario2 %}
      <tr>

                     <td>{{ usuario.id }}</td>
                     <td>{{ usuario.nombre }}</td>
                     <td>{{ usuario.apellidos }}</td>
                     <td>{{ usuario.cedula }}</td>
                     <td>{{ usuario.programa}}</td>
                     <td>{{ usuario.uid}}</td>
                     <td>{{ usuario.saldo}}</td>

                     			<td>
                     				<a class="btn btn-primary" href="{% url  'usuarios:crear_trans' usuario.id %}">Transaccion</a>
                            <!-- <a class="btn btn-primary" href="{% url 'rfid:saldo_editar' usuario.id %}">Editar</a>   --->
                     			</td>
                     		</tr>




   {% endfor %}
	<tr>

    {% else %}

   		<h1>No hay registros disponibles </h1>
    


   {% endif %}


	</tbody>
</table>
{% endblock%}

ADMIN LTE

templates/rfid/cupos.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">


<table  width="100%" class="table table-striped table-bordered table-hover" id="mytable">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Cupos totales</th>
      <th scope="col">Cupos Desayuno</th>
      <th scope="col">Cupos Almuerzo</th>
      <th scope="col">Cupos Cena </th>
      <th scope="col">Cupos Disponibles</th>
        <th scope="col">Cupos Vendidos</th>
      <th scope="col">Reservas no Redimidas</th>
      <th scope="col">Fecha </th>
<br>
<h2> Lista de cupos   </h2>



<br>

    </tr>
  </thead>


	<tbody>
		{% if usuario2 %}
		{% for usuario in usuario2 %}
		<tr>
			<td>{{ usuario.id }}</td>
      <td>{{ usuario.cupos_totales }}</td>
      <td>{{ usuario.cupos_desayuno }}</td>
      <td>{{ usuario.cupos_almuerzo }}</td>
      <td>{{ usuario.cupos_cena }}</td>
      <td>{{ usuario.cupos_disponibles}}</td>
      <td>{{ usuario.cupos_vendidos}}</td>
      <td>{{ usuario.reservas_no_redimidas}}</td>
      <td>{{ usuario.fecha_de_transaccion}}</td>





		{% endfor %}

		{% else %}
		<h1>No hay registros de cupos disponibles </h1>
		{% endif %}
	</tbody>
</table>
{% endblock%}


{% block footer %}
    {%  if servicio == "almuerzo" %}


    <br>
    <br>


    <div class="container">
    <h4 class="text-center">  Pasar reservas no redimidas a reclamadas para ventas de  {{ servicio  }}   </h4>

      <div class="row justify-content-center">
          <form class="form-center"    action="/Rfid/redimir" >
            <button class="btn btn-success"  type="submit">REDIMIR</button>
          </form>


    <br>
    <br>

    {%  elif servicio == "desayuno" %}


    <br>
    <br>


    <div class="container">
    <h4 class="text-center">  Pasar reservas no redimidas a reclamadas para ventas de  {{ servicio  }}    </h4>

      <div class="row justify-content-center">
          <form class="form-center"    action="/Rfid/redimir" >
            <button class="btn btn-success"  type="submit">REDIMIR</button>
          </form>


    <br>
    <br>
    {%  elif servicio == "almuerzo" %}


    <br>
    <br>


    <div class="container">
    <h4 class="text-center">  Pasar reservas no redimidas a reclamadas para ventas   </h4>

      <div class="row justify-content-center">
          <form class="form-center"    action="/Rfid/redimir" >
            <button class="btn btn-success"  type="submit">REDIMIR</button>
          </form>


    <br>
    <br>


    {%  elif servicio == "cena" %}


    <br>
    <br>


    <div class="container">
    <h4 class="text-center">  Pasar reservas no redimidas a reclamadas para ventas de  {{ servicio  }}    </h4>

      <div class="row justify-content-center">
          <form class="form-center"    action="/Rfid/redimir" >
            <button class="btn btn-success"  type="submit">REDIMIR</button>
          </form>


    <br>
    <br>
    {% else %}





{% endif %}
{% endblock%}

templates/rfid/identificador_autorizacion.html
{% extends 'base/base.html' %}

{% block title %} Autorizar rfid  {% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
  <div class="jumbotron">
    <h3 class="text-center">IDENTIFICADOR RFID 2  <div class="col-12"</h3>

      <form class="form-center"    action="/Rfid/Autorizar" >
        <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">ACTIVAR</button>
      </form>

  </div>
    </div>
      </div>




{% endblock%}




{% block footer %}
<div class="container">




   {% if usuario2  %}


      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">apellidos</th>
            <th scope="col">cedula</th>
            <th scope="col">programa </th>
            <th scope="col">Uid</th>
            <th scope="col">Saldo</th>
            <th scope="col">Acciones</th>




           </tr>

         </thead>
         <tbody>

   {% for usuario in usuario2 %}
      <tr>

                     <td>{{ usuario.id }}</td>
                     <td>{{ usuario.nombre }}</td>
                     <td>{{ usuario.apellidos }}</td>
                     <td>{{ usuario.cedula }}</td>
                     <td>{{ usuario.programa}}</td>
                     <td>{{ usuario.uid}}</td>
                     <td>{{ usuario.saldo}}</td>

                           <td>
                             <a class="btn btn-primary" href="{% url  'usuarios:crear_trans' usuario.id %}">Transaccion</a>
                            <!-- <a class="btn btn-primary" href="{% url 'rfid:saldo_editar' usuario.id %}">Editar</a>   --->
                           </td>
                         </tr>




   {% endfor %}
 <tr>

    {% else %}

       <h1>No hay registros disponibles </h1>



   {% endif %}


 </tbody>
</table>
{% endblock%}

templates/rfid/identificador_rfid.html
{% extends 'base/base.html' %}

{% block title %} Identificador rfid  {% endblock %}














{% block content %}


<p id="parrafo" title="Soy el titulo del parrafo"> Yo amo a Javascript </p>



<div id="prueba" url-dentro="{% url 'rfid:index3' %}"></div>

<script type="text/javascript">




       $(document).ready(function(){
          var url = $("#rprueba").attr('url-dentro');
          var titulo = $("#parrafo").attr('title');
          function readProveedor() {
            $.ajax({
              url: url,

              success: function(data){
                $("#prueba").html(data)
                alert(titulo);

              }
            });
          }
          var inter = setInterval(readProveedor, 3000);
        });


      </script>




<div class="container">
  <div class="row justify-content-center">
  <div class="jumbotron">
    <h3 class="text-center">IDENTIFICADOR RFID  <div class="col-12"</h3>

      <form class="form-center"    action="/Rfid/inicio/lectura/" >
        <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">ACTIVAR</button>
      </form>

  </div>
    </div>
      </div>



{% endblock%}




















{% block footer %}
<div class="container">




   {% if usuario2  %}


      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">apellidos</th>
            <th scope="col">cedula</th>
            <th scope="col">programa </th>
            <th scope="col">Uid</th>
            <th scope="col">Saldo</th>
            <th scope="col">Acciones</th>




           </tr>

         </thead>
         <tbody>

   {% for usuario in usuario2 %}
      <tr>

                     <td>{{ usuario.id }}</td>
                     <td>{{ usuario.nombre }}</td>
                     <td>{{ usuario.apellidos }}</td>
                     <td>{{ usuario.cedula }}</td>
                     <td>{{ usuario.programa}}</td>
                     <td>{{ usuario.uid}}</td>
                     <td>{{ usuario.saldo}}</td>

                           <td>
                             <a class="btn btn-primary" href="{% url  'usuarios:crear_trans' usuario.id %}">Transaccion</a>
                            <!-- <a class="btn btn-primary" href="{% url 'rfid:saldo_editar' usuario.id %}">Editar</a>   --->
                           </td>
                         </tr>




   {% endfor %}
 <tr>

    {% else %}

       <h1>No hay registros disponibles </h1>



   {% endif %}


 </tbody>
</table>
{% endblock%}